### **Numpy**

In [3]:
import numpy as np

### **Arrays**

In [4]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
#3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
#3D
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [8]:
np.arange(1,11,2)  

array([1, 3, 5, 7, 9])

In [9]:
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.random.random((3,4))

array([[0.93016   , 0.56540453, 0.20170996, 0.85496805],
       [0.25674715, 0.95230577, 0.59336826, 0.64645656],
       [0.42935313, 0.58040738, 0.04327216, 0.72776252]])

In [13]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [14]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

 ### **array attrributes**

In [15]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [16]:
a3.ndim

3

In [17]:
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [18]:
print(a2.size)
a2 

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [19]:
a1.itemsize

4

In [20]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


### **changing datatype**

In [21]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### **Array Operations**

In [22]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [23]:
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [24]:
a2 == 16

array([[False, False, False, False],
       [ True, False, False, False],
       [False, False, False, False]])

In [25]:
a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

### **Array Functions**

In [26]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[86., 82.,  4.],
       [40., 89.,  4.],
       [34.,  6., 70.]])

In [27]:
np.max(a1,axis=1)

array([86., 89., 70.])

In [28]:
np.prod(a1,axis=1)

array([28208., 14240., 14280.])

In [29]:
np.mean(a1,axis=1)

array([57.33333333, 44.33333333, 36.66666667])

In [30]:
np.median(a1,axis=1)


array([82., 40., 34.])

In [31]:
np.std(a1,axis=1)

array([37.74770045, 34.83612429, 26.19584361])

In [32]:
np.var(a1,axis=1)

array([1424.88888889, 1213.55555556,  686.22222222])

In [33]:
np.sin(a1)

array([[-0.92345845,  0.31322878, -0.7568025 ],
       [ 0.74511316,  0.86006941, -0.7568025 ],
       [ 0.52908269, -0.2794155 ,  0.77389068]])

In [34]:
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [35]:
np.log(a1)

array([[4.4543473 , 4.40671925, 1.38629436],
       [3.68887945, 4.48863637, 1.38629436],
       [3.52636052, 1.79175947, 4.24849524]])

In [36]:
np.exp(a1)

array([[2.23524660e+37, 4.09399696e+35, 5.45981500e+01],
       [2.35385267e+17, 4.48961282e+38, 5.45981500e+01],
       [5.83461743e+14, 4.03428793e+02, 2.51543867e+30]])

In [37]:
np.round(np.random.random((2,3))*100)

array([[98., 86., 47.],
       [ 3., 27., 89.]])

In [38]:
np.floor(np.random.random((2,3))*100)

array([[33.,  9., 25.],
       [41., 78., 14.]])

In [39]:
np.ceil(np.random.random((2,3))*100)

array([[75., 99., 48.],
       [99., 76., 16.]])

### **indexing and slicing**

In [40]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [41]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
a1[-1]

np.int64(9)

In [43]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
a2[1,2]

np.int64(6)

In [45]:
a2[2,3]

np.int64(11)

In [46]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [47]:
a3[1,0,1]

np.int64(5)

In [48]:
a3[0,1,0]

np.int64(2)

In [49]:
a3[0,0,0]

np.int64(0)

In [50]:
a3[1,1,0]

np.int64(6)

In [51]:
a1[2:5]

array([2, 3, 4])

In [52]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
a2[0,:]

array([0, 1, 2, 3])

In [54]:
a2[:,2]

array([ 2,  6, 10])

In [55]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [56]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [57]:
a2[1:2,::3]

array([[4, 7]])

In [58]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [59]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [60]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [61]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

### **itertitng**

In [62]:
a1

for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [63]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [64]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [65]:
a3 

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [66]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [67]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### **Reshape**

In [68]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [69]:
a2.ravel()
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### **Stacking**

In [70]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [71]:
np.hstack((a4,a5,a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11, 20, 21, 22, 23]])

In [72]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### **Splitting**

In [73]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [74]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [75]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [76]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [84]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]