### **Numpy**

In [2]:
import numpy as np

### **Arrays**

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
#3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
#3D
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [9]:
np.arange(1,11,2)  

array([1, 3, 5, 7, 9])

In [15]:
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.random.random((3,4))

array([[0.69935888, 0.00303303, 0.71512885, 0.2734018 ],
       [0.76082072, 0.40216811, 0.9601594 , 0.00550255],
       [0.97370711, 0.56425752, 0.80203331, 0.47816244]])

In [21]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [22]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])