### **Numpy**

In [2]:
import numpy as np

### **Arrays**

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
#3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
#3D
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [7]:
np.arange(1,11,2)  

array([1, 3, 5, 7, 9])

In [8]:
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [9]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.random.random((3,4))

array([[0.33986671, 0.09772297, 0.19644857, 0.53393441],
       [0.87490195, 0.80053951, 0.96092607, 0.29061808],
       [0.43140203, 0.22314889, 0.75005928, 0.42652886]])

In [12]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [13]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

 ### **array attrributes**

In [14]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [15]:
a3.ndim

3

In [16]:
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [17]:
print(a2.size)
a2 

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [18]:
a1.itemsize

4

In [19]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


### **changing datatype**

In [20]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### **Array Operations**

In [21]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [22]:
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [23]:
a2 == 16

array([[False, False, False, False],
       [ True, False, False, False],
       [False, False, False, False]])

In [24]:
a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

### **Array Functions**

In [25]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[76., 63.,  4.],
       [47., 91., 42.],
       [85., 15., 47.]])

In [26]:
np.max(a1,axis=1)

array([76., 91., 85.])

In [27]:
np.prod(a1,axis=1)

array([ 19152., 179634.,  59925.])

In [28]:
np.mean(a1,axis=1)

array([47.66666667, 60.        , 49.        ])

In [29]:
np.median(a1,axis=1)


array([63., 47., 47.])

In [30]:
np.std(a1,axis=1)

array([31.32978703, 22.0151463 , 28.61235165])

In [31]:
np.var(a1,axis=1)

array([981.55555556, 484.66666667, 818.66666667])

In [32]:
np.sin(a1)

array([[ 0.56610764,  0.1673557 , -0.7568025 ],
       [ 0.12357312,  0.10598751, -0.91652155],
       [-0.17607562,  0.65028784,  0.12357312]])

In [33]:
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [34]:
np.log(a1)

array([[4.33073334, 4.14313473, 1.38629436],
       [3.8501476 , 4.51085951, 3.73766962],
       [4.44265126, 2.7080502 , 3.8501476 ]])

In [35]:
np.exp(a1)

array([[1.01480039e+33, 2.29378316e+27, 5.45981500e+01],
       [2.58131289e+20, 3.31740010e+39, 1.73927494e+18],
       [8.22301271e+36, 3.26901737e+06, 2.58131289e+20]])

In [36]:
np.round(np.random.random((2,3))*100)

array([[36., 50., 12.],
       [85., 33., 36.]])

In [37]:
np.floor(np.random.random((2,3))*100)

array([[53., 41., 31.],
       [97.,  1., 76.]])

In [38]:
np.ceil(np.random.random((2,3))*100)

array([[ 2., 71., 95.],
       [76., 44., 46.]])

### **indexing and slicing**

In [39]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [40]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a1[-1]

np.int64(9)

In [42]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
a2[1,2]

np.int64(6)

In [44]:
a2[2,3]

np.int64(11)

In [45]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [46]:
a3[1,0,1]

np.int64(5)

In [47]:
a3[0,1,0]

np.int64(2)

In [48]:
a3[0,0,0]

np.int64(0)

In [49]:
a3[1,1,0]

np.int64(6)

In [50]:
a1[2:5]

array([2, 3, 4])

In [51]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
a2[0,:]

array([0, 1, 2, 3])

In [53]:
a2[:,2]

array([ 2,  6, 10])

In [54]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [55]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [56]:
a2[1:2,::3]

array([[4, 7]])

In [57]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [58]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [59]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [60]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

### **itertitng**

In [61]:
a1

for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [62]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [63]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [64]:
a3 

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [65]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [66]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### **Reshape**

In [67]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [68]:
a2.ravel()
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### **Stacking**

In [69]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [70]:
np.hstack((a4,a5,a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11, 20, 21, 22, 23]])

In [71]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### **Splitting**

In [72]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [73]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [74]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [75]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [76]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

### **Numpy array vs python lists**

In [77]:
a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]

c = []
import time

start = time.time()
for i in range(len(a)):
    c.append(a[i] + b[i])
print(time.time()-start)

1.4202628135681152


In [78]:
import numpy as np
a = np.arange(10000000)
b = np.arange(10000000,20000000)

start = time.time()
c = a + b
print(time.time()-start)

0.14244318008422852


In [79]:
3.26/0.06

54.33333333333333

In [80]:
a = [i for i in range(10000000)]
import sys

sys.getsizeof(a)

89095160

In [81]:
a = np.arange(10000000,dtype=np.int8)
sys.getsizeof(a)

10000112

### **advanced indexing**

In [82]:
a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [83]:
a[1,2]

np.int64(6)

In [84]:
a[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [85]:
a[[0,2,3]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [86]:
a[[0,2,3,5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [87]:
a[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [88]:
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[ 9,  9, 90, 35],
       [38, 25, 68, 18],
       [68, 15, 65, 99],
       [77,  3, 96, 23],
       [94, 11, 96, 53],
       [91, 71, 64, 31]])

In [89]:
a > 50


array([[False, False,  True, False],
       [False, False,  True, False],
       [ True, False,  True,  True],
       [ True, False,  True, False],
       [ True, False,  True,  True],
       [ True,  True,  True, False]])

In [90]:
a[a > 50]

array([90, 68, 68, 65, 99, 77, 96, 94, 96, 53, 91, 71, 64])

In [91]:
a % 2 == 0

array([[False, False,  True, False],
       [ True, False,  True,  True],
       [ True, False, False, False],
       [False, False,  True, False],
       [ True, False,  True, False],
       [False, False,  True, False]])

In [92]:
a[a % 2 == 0]

array([90, 38, 68, 18, 68, 96, 94, 96, 64])

In [93]:
(a > 50) & (a % 2 == 0)

array([[False, False,  True, False],
       [False, False,  True, False],
       [ True, False, False, False],
       [False, False,  True, False],
       [ True, False,  True, False],
       [False, False,  True, False]])

In [94]:
a [(a > 50) & (a % 2 == 0)]

array([90, 68, 68, 96, 94, 96, 64])

In [95]:
a[a % 7 == 0]

array([35, 77, 91])

In [96]:
a[~(a % 7 == 0)]

array([ 9,  9, 90, 38, 25, 68, 18, 68, 15, 65, 99,  3, 96, 23, 94, 11, 96,
       53, 71, 64, 31])

### **Broadcasting**

In [97]:
a  = np.arange(6).reshape(2,3)
b  = np.arange(6,12).reshape(2,3)

print(a)
print(b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [98]:
a  = np.arange(6).reshape(2,3)
b  = np.arange(3).reshape(1,3)

print(a)
print(b)

print(a+b)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]
[[0 2 4]
 [3 5 7]]


### **Broadcasting Rules**
1. Make the two arrays have the same number of dimensions

If the numbers of dimensions of the two arrays are different, add new dimensions with size 1 to the head of the array with the smaller dimension.



2. Make each dimension of the two arrays the same size.

If the sizes of each dimension of the two arrays do not match, dimensions with size 1 are stretched to the size of the other array.
If there is a dimension whose size is not 1 in either of the two arrays, it cannot be broadcasted, and an error is raised.


<img src = "https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png">

In [99]:
a = np.arange(12).reshape(4,3)
b = np.arange(3)

print(a)
print(b)

print(a+b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [102]:
a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)

print(a)
print(b)

print(a+b)

[[0 1 2]]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [104]:
a = np.arange(3).reshape(1,3)
b = np.arange(4).reshape(4,1)

print(a)
print(b)

print(a + b)

[[0 1 2]]
[[0]
 [1]
 [2]
 [3]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


### **Working with mathematical formulas**

In [109]:
a = np.arange(10)
np.sin(a) #sin,cos,than,sum,etc...

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [106]:
# sigmoid
def sigmoid(array):
  return 1/(1 + np.exp(-(array)))


a = np.arange(100)

sigmoid(a)

array([0.5       , 0.73105858, 0.88079708, 0.95257413, 0.98201379,
       0.99330715, 0.99752738, 0.99908895, 0.99966465, 0.99987661,
       0.9999546 , 0.9999833 , 0.99999386, 0.99999774, 0.99999917,
       0.99999969, 0.99999989, 0.99999996, 0.99999998, 0.99999999,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.     

In [111]:
# mean squared error

actual = np.random.randint(1,50,25)
predicted = np.random.randint(1,50,25)

def mse(actual,predicted):
  return np.mean((actual - predicted)**2)

mse(actual,predicted)

np.float64(451.68)