### **Numpy**

In [2]:
import numpy as np

### **Arrays**

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
#3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
#3D
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [7]:
np.arange(1,11,2)  

array([1, 3, 5, 7, 9])

In [8]:
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [9]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.random.random((3,4))

array([[0.17501145, 0.54352283, 0.3983066 , 0.09589109],
       [0.01888792, 0.75854109, 0.98892198, 0.28699172],
       [0.53144068, 0.65362334, 0.39804869, 0.62182576]])

In [12]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [13]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

 ### **array attrributes**

In [14]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [15]:
a3.ndim

3

In [16]:
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [17]:
print(a2.size)
a2 

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [18]:
a1.itemsize

4

In [19]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


### **changing datatype**

In [20]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### **Array Operations**

In [21]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [22]:
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [23]:
a2 == 16

array([[False, False, False, False],
       [ True, False, False, False],
       [False, False, False, False]])

In [24]:
a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

### **Array Functions**

In [25]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[38., 85., 28.],
       [34., 31., 66.],
       [83., 24., 65.]])

In [26]:
np.max(a1,axis=1)

array([85., 66., 83.])

In [27]:
np.prod(a1,axis=1)

array([ 90440.,  69564., 129480.])

In [28]:
np.mean(a1,axis=1)

array([50.33333333, 43.66666667, 57.33333333])

In [29]:
np.median(a1,axis=1)


array([38., 34., 65.])

In [30]:
np.std(a1,axis=1)

array([24.85066509, 15.83947249, 24.68917892])

In [31]:
np.var(a1,axis=1)

array([617.55555556, 250.88888889, 609.55555556])

In [32]:
np.sin(a1)

array([[ 0.29636858, -0.17607562,  0.27090579],
       [ 0.52908269, -0.40403765, -0.02655115],
       [ 0.96836446, -0.90557836,  0.82682868]])

In [33]:
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [34]:
np.log(a1)

array([[3.63758616, 4.44265126, 3.33220451],
       [3.52636052, 3.4339872 , 4.18965474],
       [4.41884061, 3.17805383, 4.17438727]])

In [35]:
np.exp(a1)

array([[3.18559318e+16, 8.22301271e+36, 1.44625706e+12],
       [5.83461743e+14, 2.90488497e+13, 4.60718663e+28],
       [1.11286375e+36, 2.64891221e+10, 1.69488924e+28]])

In [36]:
np.round(np.random.random((2,3))*100)

array([[17., 70., 21.],
       [96., 18., 41.]])

In [37]:
np.floor(np.random.random((2,3))*100)

array([[46., 30., 14.],
       [72., 18.,  5.]])

In [38]:
np.ceil(np.random.random((2,3))*100)

array([[77., 96.,  2.],
       [86., 74., 95.]])

### **indexing and slicing**

In [40]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [41]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
a1[-1]

np.int64(9)

In [43]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
a2[1,2]

np.int64(6)

In [47]:
a2[2,3]

np.int64(11)

In [48]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

### **itertitng**