### **Numpy**

In [2]:
import numpy as np

### **Arrays**

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
#3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
#3D
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [9]:
np.arange(1,11,2)  

array([1, 3, 5, 7, 9])

In [15]:
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.random.random((3,4))

array([[0.69935888, 0.00303303, 0.71512885, 0.2734018 ],
       [0.76082072, 0.40216811, 0.9601594 , 0.00550255],
       [0.97370711, 0.56425752, 0.80203331, 0.47816244]])

In [21]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [22]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

 ### **array attrributes**

In [34]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [25]:
a3.ndim

3

In [27]:
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [28]:
print(a2.size)
a2 

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [35]:
a1.itemsize

4

In [36]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


### **changing datatype**

In [38]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### **Array Operations**

In [39]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [40]:
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [41]:
a2 == 16

array([[False, False, False, False],
       [ True, False, False, False],
       [False, False, False, False]])

In [43]:
a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

### **Array Functions**

In [45]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[53., 45., 65.],
       [59., 65., 64.],
       [67., 46., 55.]])

In [47]:
np.max(a1,axis=1)

array([65., 65., 67.])

In [48]:
np.prod(a1,axis=1)

array([155025., 245440., 169510.])

In [50]:
np.mean(a1,axis=1)

array([54.33333333, 62.66666667, 56.        ])

In [ ]:
np.median(a1,axis=1)


array([53., 64., 55.])

In [52]:
np.std(a1,axis=1)

array([8.21921867, 2.62466929, 8.60232527])

In [53]:
np.var(a1,axis=1)

array([67.55555556,  6.88888889, 74.        ])

In [54]:
np.sin(a1)

array([[ 0.39592515,  0.85090352,  0.82682868],
       [ 0.63673801,  0.82682868,  0.92002604],
       [-0.85551998,  0.90178835, -0.99975517]])

In [57]:
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [58]:
np.log(a1)

array([[3.97029191, 3.80666249, 4.17438727],
       [4.07753744, 4.17438727, 4.15888308],
       [4.20469262, 3.8286414 , 4.00733319]])

In [59]:
np.exp(a1)

array([[1.04137594e+23, 3.49342711e+19, 1.69488924e+28],
       [4.20121040e+25, 1.69488924e+28, 6.23514908e+27],
       [1.25236317e+29, 9.49611942e+19, 7.69478527e+23]])

In [60]:
np.round(np.random.random((2,3))*100)

array([[67., 85., 62.],
       [84., 88., 23.]])

In [61]:
np.floor(np.random.random((2,3))*100)

array([[95., 38., 49.],
       [84., 56., 47.]])

In [63]:
np.ceil(np.random.random((2,3))*100)

array([[68., 18., 94.],
       [70., 22., 51.]])

### **indexing and slicing**