### **Numpy**

In [2]:
import numpy as np

### **Arrays**

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
#3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
#3D
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
