### **Numpy**

In [1]:
import numpy as np

### **Arrays**

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
#3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
#3D
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [6]:
np.arange(1,11,2)  

array([1, 3, 5, 7, 9])

In [7]:
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [8]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.random.random((3,4))

array([[0.149456  , 0.677374  , 0.32225992, 0.85258716],
       [0.19276416, 0.2250818 , 0.77022943, 0.41724454],
       [0.33233595, 0.23491874, 0.73525317, 0.18899319]])

In [11]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [12]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

 ### **array attrributes**

In [13]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [14]:
a3.ndim

3

In [15]:
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [16]:
print(a2.size)
a2 

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [17]:
a1.itemsize

4

In [18]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


### **changing datatype**

In [19]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### **Array Operations**

In [20]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [21]:
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [22]:
a2 == 16

array([[False, False, False, False],
       [ True, False, False, False],
       [False, False, False, False]])

In [23]:
a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

### **Array Functions**

In [24]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[76., 30., 93.],
       [31.,  6., 91.],
       [99., 78.,  5.]])

In [25]:
np.max(a1,axis=1)

array([93., 91., 99.])

In [26]:
np.prod(a1,axis=1)

array([212040.,  16926.,  38610.])

In [27]:
np.mean(a1,axis=1)

array([66.33333333, 42.66666667, 60.66666667])

In [28]:
np.median(a1,axis=1)


array([76., 31., 78.])

In [29]:
np.std(a1,axis=1)

array([26.61244487, 35.66822427, 40.28509512])

In [30]:
np.var(a1,axis=1)

array([ 708.22222222, 1272.22222222, 1622.88888889])

In [31]:
np.sin(a1)

array([[ 0.56610764, -0.98803162, -0.94828214],
       [-0.40403765, -0.2794155 ,  0.10598751],
       [-0.99920683,  0.51397846, -0.95892427]])

In [32]:
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [33]:
np.log(a1)

array([[4.33073334, 3.40119738, 4.53259949],
       [3.4339872 , 1.79175947, 4.51085951],
       [4.59511985, 4.35670883, 1.60943791]])

In [34]:
np.exp(a1)

array([[1.01480039e+33, 1.06864746e+13, 2.45124554e+40],
       [2.90488497e+13, 4.03428793e+02, 3.31740010e+39],
       [9.88903032e+42, 7.49841700e+33, 1.48413159e+02]])

In [35]:
np.round(np.random.random((2,3))*100)

array([[43., 97., 60.],
       [86., 89., 63.]])

In [36]:
np.floor(np.random.random((2,3))*100)

array([[50., 37., 79.],
       [14., 94., 99.]])

In [37]:
np.ceil(np.random.random((2,3))*100)

array([[73., 78., 75.],
       [76., 70., 58.]])

### **indexing and slicing**

In [38]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [39]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
a1[-1]

np.int64(9)

In [41]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
a2[1,2]

np.int64(6)

In [43]:
a2[2,3]

np.int64(11)

In [44]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [45]:
a3[1,0,1]

np.int64(5)

In [46]:
a3[0,1,0]

np.int64(2)

In [47]:
a3[0,0,0]

np.int64(0)

In [48]:
a3[1,1,0]

np.int64(6)

In [49]:
a1[2:5]

array([2, 3, 4])

In [50]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
a2[0,:]

array([0, 1, 2, 3])

In [52]:
a2[:,2]

array([ 2,  6, 10])

In [53]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [54]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [55]:
a2[1:2,::3]

array([[4, 7]])

In [56]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [57]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [58]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [59]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

### **itertitng**